# Generated by Django 4.0.7 on 2022-11-29 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasVacantes',
            fields=[
                ('IdCategoriaVacante', models.AutoField(primary_key=True, serialize=False)),
                ('CategoriaVacante', models.CharField(max_length=100, verbose_name='Categoría de la vacante')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('IdVacante', models.AutoField(primary_key=True, serialize=False)),
                ('TituloVacante', models.CharField(max_length=30, verbose_name='Titulo_Vacante')),
                ('Pago', models.FloatField(blank=True, null=True, verbose_name='Pago')),
                ('DescripcionVacante', models.TextField(verbose_name='Descripción de la vacante')),
                ('FechaPublicacionVacante', models.DateField(default=django.utils.timezone.now)),
                ('AutorVacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_vacante', to=settings.AUTH_USER_MODEL)),
                ('CategoriaVacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_vacante', to='vacantes.categoriasvacantes')),
            ],
        ),
    ]
