# Generated by Django 4.1.2 on 2022-11-30 19:50

import apps.publicaciones.models
import apps.publicaciones.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPublicacion',
            fields=[
                ('IdCatePub', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCatPub', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.publicaciones.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.publicaciones.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('IdPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=30, verbose_name='Titulo')),
                ('DescripcionPublicacion', models.TextField(verbose_name='Descripción de la publicación')),
                ('FechaPublicacion', models.DateField(default=django.utils.timezone.now)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_publicacion', to=settings.AUTH_USER_MODEL)),
                ('Multimedia_Img', models.ManyToManyField(blank=True, to='publicaciones.imagen')),
                ('Multimedia_Video', models.ManyToManyField(blank=True, to='publicaciones.video', validators=[apps.publicaciones.validators.file_size])),
                ('PerfilAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_autor_publicacion', to='Usuarios.perfil')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerteneceACategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCatePub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.categoriapublicacion')),
                ('IdPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('IdComentario', models.AutoField(primary_key=True, serialize=False)),
                ('Comentario', models.TextField()),
                ('FechaComment', models.DateField(default=django.utils.timezone.now)),
                ('IdPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_comentario', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
